# Generated by Django 5.2.2 on 2025-06-09 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transactionhistory",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.account",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["user"], name="account_user_id_5ee0be_idx"),
        ),
        migrations.AddIndex(
            model_name="transactionhistory",
            index=models.Index(
                fields=["account"], name="transaction_account_752a22_idx"
            ),
        ),
    ]
