# Generated by Django 5.2.2 on 2025-06-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="balance",
            field=models.DecimalField(
                decimal_places=0, max_digits=18, verbose_name="BALANCE"
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[("IN", "입금"), ("OUT", "출금")],
                max_length=10,
                verbose_name="Transaction Type",
            ),
        ),
    ]
