# Generated by Django 5.2.2 on 2025-06-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_transactionhistory_post_transaction_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionhistory",
            name="balance",
            field=models.DecimalField(
                decimal_places=0, max_digits=18, verbose_name="Post Transaction Amount"
            ),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="transaction_amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=18, verbose_name="Transaction Amount"
            ),
        ),
    ]
