# Generated by Django 5.2.2 on 2025-06-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_transactionhistory_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionhistory",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transactionhistory",
            name="balance",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=18,
                verbose_name="Balance After Transaction",
            ),
        ),
    ]
