# Generated by Django 5.2.2 on 2025-06-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_transactionhistory_is_canceled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transactionhistory",
            name="transaction_details",
        ),
    ]
